[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "haskell-tree-sitter"
version = "0.1.0"
description = "Haskell tree-sitter support for CocoIndex"
requires-python = ">=3.11"
dependencies = [
    "cocoindex[embeddings]>=0.1.63", 
    "python-dotenv>=1.0.1",
    "psycopg[pool]",
    "pgvector",
    "numpy",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "haskell_tree_sitter"
