# generated with `stubgen -p haskell_tree_sitter`

def debug_haskell_ast_nodes(*args, **kwargs): ...
def get_haskell_ast_chunks(*args, **kwargs): ...
def get_haskell_ast_chunks_with_fallback(*args, **kwargs): ...
def get_haskell_separators(*args, **kwargs): ...
def parse_haskell(*args, **kwargs): ...
